let cartas = [
  { id: "C001", texto: "D.Afonso Henriques atacou a mãe porque era um adolescente com problemas" },
  { id: "C003", texto: "\"Descoberta\" do Brasil." },
  { id: "C004", texto: "Cabo da Boa Esperança" },
  { id: "C005", texto: "Zé Povinho." },
  { id: "C006", texto: "Máfia da Amadora." },
  { id: "C007", texto: "Mata de Sintra." },
  { id: "C008", texto: "Destruir os sonhos de um vencedor do The Voice." },
  { id: "C009", texto: "Uma alface da horta da horta da tua avó." },
  { id: "C010", texto: "Uma pila a cair de podre." },
  { id: "C011", texto: "Vizinhos a foder a meio da noite." },
  { id: "C012", texto: "Ter a primeira experiência sexual com um galo." },
  { id: "C013", texto: "A tua mãe de quatro" },
  { id: "C014", texto: "Suor debaixo das mamas" },
  { id: "C015", texto: "Sandes de esperma" },
  { id: "C016", texto: "O hino nacional cantado pelos anjos" },
  { id: "C017", texto: "Um contentor do lixo com 50 litros de lubrificante" },
  { id: "C018", texto: "Um polícia a comer um iogurde sem colher" },
  { id: "C019", texto: "Uma caralhada qualquer" },
  { id: "C020", texto: "o caralho" },
  { id: "C021", texto: "sexo tântrico" },
  { id: "C022", texto: "Uma pila cheia de varizes" },
  { id: "C023", texto: "Eutanasiar velhos com gripe" },
  { id: "C024", texto: "o corpo sexy de Salazar." },
  { id: "C025", texto: "O fogão do homem do Goucha" },
  { id: "C026", texto: "Iniciar a reconquista de Angola" },
  { id: "C027", texto: "amar Allah" },
  { id: "C028", texto: "Alucinações" },
  { id: "C029", texto: "Esconder herpes com pelos da cona" },
  { id: "C030", texto: "uma câmara de gás" },
  { id: "C031", texto: "ouvir discursos motivacionais" },
  { id: "C032", texto: "chuva ácida a derreter a pele dos ossos" },
  { id: "C033", texto: "ter um caso com a psicóloga" },
  { id: "C034", texto: "Chantagear" },
  { id: "C035", texto: "morrer de cancro dos pulmões" },
  { id: "C036", texto: "a ciência das ereções" },
  { id: "C037", texto: "o comité olimpico" },
  { id: "C038", texto: "a comunidade muçulmana" },
  { id: "C039", texto: "ter um tumor cerebral do tamanho de uma melancia" },
  { id: "C040", texto: "democracia" },
  { id: "C041", texto: "monarquia" },
  { id: "C042", texto: "violência doméstica" },
  { id: "C043", texto: "injetar heroína" },
  { id: "C044", texto: "ajudar pessoas" },
  { id: "C045", texto: "uma sanita que fala" },
  { id: "C046", texto: "fazer sexo com uma mulher com as luzes desligadas e acordar a saber que era o teu cão" },
  { id: "C047", texto: "tornar-se pai porque ela se esqueceu da pílula" },
  { id: "C048", texto: "a casa de grelhados do hitler" },
  { id: "C049", texto: "fazer clones de mim mesmo para usar como alibi" },
  { id: "C050", texto: "ser enterrado vivo" },
  { id: "C051", texto: "o presidente da republica" },
  { id: "C052", texto: "olhar para a barba de um homem e reparar que tem esperma" },
  { id: "C053", texto: "zombies" },
  { id: "C054", texto: "uma desculpa formal" },
  { id: "C055", texto: "animais gays" },
  { id: "C056", texto: "negar algo mesmo quando há provas em vídeo" },
  { id: "C057", texto: "encontrar alguem durante um concerto" },
  { id: "C058", texto: "aquele amigo \"especial\"" },
  { id: "C059", texto: "dizer que é intolerante à lactose" },
  { id: "C060", texto: "usar a irmã como preservativo" },
  { id: "C061", texto: "pessoas chinesas" },
  { id: "C062", texto: "pansexuais" },
  { id: "C063", texto: "bissexuais" },
  { id: "C064", texto: "dizer coisas porcas em linguagem gestual" },
  { id: "C065", texto: "um africano albino" },
  { id: "C066", texto: "o que os homens fazem para passar tempo na prisão" },
  { id: "C067", texto: "esquecer-se de ser bonzinho" },
  { id: "C068", texto: "fazer revisões para um teste que consideras inutil" },
  { id: "C069", texto: "escorregar e acidentalmente penetrá-la" },
  { id: "C070", texto: "adolescentes excitados a ejacular em todo o lado" },
  { id: "C071", texto: "estudar" },
  { id: "C072", texto: "um brasileiro" },
  { id: "C073", texto: "um angolano" },
  { id: "C074", texto: "chegar à conclusão que és um merdas" },
  { id: "C075", texto: "ter de reutilizar um preservativo" },
  { id: "C076", texto: "uma corrida mortal de cadeira de rodas" },
  { id: "C077", texto: "sindrome de down" },
  { id: "C078", texto: "descobrir que és alergico a latex durante o sexo" },
  { id: "C079", texto: "o comércio dos escravos" },
  { id: "C080", texto: "uma alergia a água" },
  { id: "C081", texto: "os bons velhos tempos" },
  { id: "C082", texto: "fazer um broche a um morto" },
  { id: "C083", texto: "zoofilia" },
  { id: "C084", texto: "ser preso por disparar acidentalmente na namorada pela porta da casa de banho" },
  { id: "C085", texto: "cona" },
  { id: "C086", texto: "um bebé feio" },
  { id: "C087", texto: "um anão a fazer striptease" },
  { id: "C088", texto: "um tatoador cego" },
  { id: "C089", texto: "espermicida" },
  { id: "C090", texto: "gays homofóbicos" },
  { id: "C091", texto: "fingir um orgasmo para ser simpático" },
  { id: "C092", texto: "uma sala cheia com as minhas ex-namoradas" },
  { id: "C093", texto: "penetração letal" },
  { id: "C094", texto: "incesto acidental" },
  { id: "C095", texto: "uma viagem gratuita para o inferno" },
  { id: "C096", texto: "um monge sem roupa" },
  { id: "C097", texto: "mijar durante o duche" },
  { id: "C098", texto: "mamilhos gigantes" },
  { id: "C099", texto: "atirar água a sem abrigos" },
  { id: "C100", texto: "hálito de prostituta" },
  { id: "C101", texto: "envenenar a ex" },
  { id: "C102", texto: "o lado bom da vida" },
  { id: "C103", texto: "ser demasiado inocente para este jogo" },
  { id: "C104", texto: "a crise de refugiados" },
  { id: "C105", texto: "tensão sexual na reunião de família" },
  { id: "C106", texto: "asiáticos a chorar porque vão comer o próprio cão ao almoço." },
  { id: "C107", texto: "trabalho infantil" },
  { id: "C108", texto: "o início do fim" },
  { id: "C109", texto: "aqueles pedaços de papel higiénico que ficam presos ao cu" },
  { id: "C110", texto: "tornar virgens em não-virgens mesmo após dizerem que não" },
  { id: "C111", texto: "virgindade anal" },
  { id: "C112", texto: "uma boa e velha garrafa de mijo" },
  { id: "C113", texto: "um cadável mais sexy que o da tua mulher" },
  { id: "C114", texto: "prostitutas da Vinted" },
  { id: "C115", texto: "masturbar-se a ver discursos de Salazar" },
  { id: "C116", texto: "Curtir com a irmã gémea da tua namorada" },
  { id: "C117", texto: "cheirar gás durante o duche" },
  { id: "C118", texto: "casar para poder foder" },
  { id: "C119", texto: "foder no lavatório da amiga" },
  { id: "C120", texto: "fodemos bué yahhh" },
  { id: "C121", texto: "dry humping" },
  { id: "C119", texto: "oh merde c'est ma femme" }
];
